services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag-api
    ports:
      - "5000:5000"
    environment:
      CHROMA_HOST: chromadb
      CHROMA_PORT: "8000"
      EMBED_MODEL: sentence-transformers/all-MiniLM-L6-v2
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      LLM_PROVIDER: ${LLM_PROVIDER:-openai}
      OLLAMA_URL: ${OLLAMA_URL:-http://host.docker.internal:11434}
    depends_on:
      - chromadb

  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - chroma_db:/chroma/chroma

  # frontend:
  #   build:
  #     context: ../rag-angular/rag-ui
  #     dockerfile: Dockerfile
  #   container_name: rag-frontend
  #   depends_on:
  #     - api

  nginx:
    image: nginx:alpine
    container_name: rag-nginx
    ports:
      - "4000:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api

volumes:
  chroma_db:
