# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.collections_response_sources import CollectionsResponseSources  # noqa: F401,E501
from swagger_server import util


class CollectionsResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, total_chunks: int=None, sources: List[CollectionsResponseSources]=None):  # noqa: E501
        """CollectionsResponse - a model defined in Swagger

        :param total_chunks: The total_chunks of this CollectionsResponse.  # noqa: E501
        :type total_chunks: int
        :param sources: The sources of this CollectionsResponse.  # noqa: E501
        :type sources: List[CollectionsResponseSources]
        """
        self.swagger_types = {
            'total_chunks': int,
            'sources': List[CollectionsResponseSources]
        }

        self.attribute_map = {
            'total_chunks': 'total_chunks',
            'sources': 'sources'
        }
        self._total_chunks = total_chunks
        self._sources = sources

    @classmethod
    def from_dict(cls, dikt) -> 'CollectionsResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CollectionsResponse of this CollectionsResponse.  # noqa: E501
        :rtype: CollectionsResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def total_chunks(self) -> int:
        """Gets the total_chunks of this CollectionsResponse.

        Total number of chunks stored across all sources  # noqa: E501

        :return: The total_chunks of this CollectionsResponse.
        :rtype: int
        """
        return self._total_chunks

    @total_chunks.setter
    def total_chunks(self, total_chunks: int):
        """Sets the total_chunks of this CollectionsResponse.

        Total number of chunks stored across all sources  # noqa: E501

        :param total_chunks: The total_chunks of this CollectionsResponse.
        :type total_chunks: int
        """
        if total_chunks is None:
            raise ValueError("Invalid value for `total_chunks`, must not be `None`")  # noqa: E501

        self._total_chunks = total_chunks

    @property
    def sources(self) -> List[CollectionsResponseSources]:
        """Gets the sources of this CollectionsResponse.


        :return: The sources of this CollectionsResponse.
        :rtype: List[CollectionsResponseSources]
        """
        return self._sources

    @sources.setter
    def sources(self, sources: List[CollectionsResponseSources]):
        """Sets the sources of this CollectionsResponse.


        :param sources: The sources of this CollectionsResponse.
        :type sources: List[CollectionsResponseSources]
        """
        if sources is None:
            raise ValueError("Invalid value for `sources`, must not be `None`")  # noqa: E501

        self._sources = sources
