# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CollectionsResponseSources(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, source: str=None, chunk_count: int=None, ingested_at: datetime=None):  # noqa: E501
        """CollectionsResponseSources - a model defined in Swagger

        :param source: The source of this CollectionsResponseSources.  # noqa: E501
        :type source: str
        :param chunk_count: The chunk_count of this CollectionsResponseSources.  # noqa: E501
        :type chunk_count: int
        :param ingested_at: The ingested_at of this CollectionsResponseSources.  # noqa: E501
        :type ingested_at: datetime
        """
        self.swagger_types = {
            'source': str,
            'chunk_count': int,
            'ingested_at': datetime
        }

        self.attribute_map = {
            'source': 'source',
            'chunk_count': 'chunk_count',
            'ingested_at': 'ingested_at'
        }
        self._source = source
        self._chunk_count = chunk_count
        self._ingested_at = ingested_at

    @classmethod
    def from_dict(cls, dikt) -> 'CollectionsResponseSources':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CollectionsResponse_sources of this CollectionsResponseSources.  # noqa: E501
        :rtype: CollectionsResponseSources
        """
        return util.deserialize_model(dikt, cls)

    @property
    def source(self) -> str:
        """Gets the source of this CollectionsResponseSources.


        :return: The source of this CollectionsResponseSources.
        :rtype: str
        """
        return self._source

    @source.setter
    def source(self, source: str):
        """Sets the source of this CollectionsResponseSources.


        :param source: The source of this CollectionsResponseSources.
        :type source: str
        """
        if source is None:
            raise ValueError("Invalid value for `source`, must not be `None`")  # noqa: E501

        self._source = source

    @property
    def chunk_count(self) -> int:
        """Gets the chunk_count of this CollectionsResponseSources.


        :return: The chunk_count of this CollectionsResponseSources.
        :rtype: int
        """
        return self._chunk_count

    @chunk_count.setter
    def chunk_count(self, chunk_count: int):
        """Sets the chunk_count of this CollectionsResponseSources.


        :param chunk_count: The chunk_count of this CollectionsResponseSources.
        :type chunk_count: int
        """
        if chunk_count is None:
            raise ValueError("Invalid value for `chunk_count`, must not be `None`")  # noqa: E501

        self._chunk_count = chunk_count

    @property
    def ingested_at(self) -> datetime:
        """Gets the ingested_at of this CollectionsResponseSources.


        :return: The ingested_at of this CollectionsResponseSources.
        :rtype: datetime
        """
        return self._ingested_at

    @ingested_at.setter
    def ingested_at(self, ingested_at: datetime):
        """Sets the ingested_at of this CollectionsResponseSources.


        :param ingested_at: The ingested_at of this CollectionsResponseSources.
        :type ingested_at: datetime
        """
        if ingested_at is None:
            raise ValueError("Invalid value for `ingested_at`, must not be `None`")  # noqa: E501

        self._ingested_at = ingested_at
