# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class HealthResponseDependenciesLlm(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, status: str=None, provider: str=None, model: str=None, error: str=None):  # noqa: E501
        """HealthResponseDependenciesLlm - a model defined in Swagger

        :param status: The status of this HealthResponseDependenciesLlm.  # noqa: E501
        :type status: str
        :param provider: The provider of this HealthResponseDependenciesLlm.  # noqa: E501
        :type provider: str
        :param model: The model of this HealthResponseDependenciesLlm.  # noqa: E501
        :type model: str
        :param error: The error of this HealthResponseDependenciesLlm.  # noqa: E501
        :type error: str
        """
        self.swagger_types = {
            'status': str,
            'provider': str,
            'model': str,
            'error': str
        }

        self.attribute_map = {
            'status': 'status',
            'provider': 'provider',
            'model': 'model',
            'error': 'error'
        }
        self._status = status
        self._provider = provider
        self._model = model
        self._error = error

    @classmethod
    def from_dict(cls, dikt) -> 'HealthResponseDependenciesLlm':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HealthResponse_dependencies_llm of this HealthResponseDependenciesLlm.  # noqa: E501
        :rtype: HealthResponseDependenciesLlm
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> str:
        """Gets the status of this HealthResponseDependenciesLlm.


        :return: The status of this HealthResponseDependenciesLlm.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this HealthResponseDependenciesLlm.


        :param status: The status of this HealthResponseDependenciesLlm.
        :type status: str
        """
        allowed_values = ["ok", "error"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def provider(self) -> str:
        """Gets the provider of this HealthResponseDependenciesLlm.


        :return: The provider of this HealthResponseDependenciesLlm.
        :rtype: str
        """
        return self._provider

    @provider.setter
    def provider(self, provider: str):
        """Sets the provider of this HealthResponseDependenciesLlm.


        :param provider: The provider of this HealthResponseDependenciesLlm.
        :type provider: str
        """
        allowed_values = ["openai", "ollama"]  # noqa: E501
        if provider not in allowed_values:
            raise ValueError(
                "Invalid value for `provider` ({0}), must be one of {1}"
                .format(provider, allowed_values)
            )

        self._provider = provider

    @property
    def model(self) -> str:
        """Gets the model of this HealthResponseDependenciesLlm.


        :return: The model of this HealthResponseDependenciesLlm.
        :rtype: str
        """
        return self._model

    @model.setter
    def model(self, model: str):
        """Sets the model of this HealthResponseDependenciesLlm.


        :param model: The model of this HealthResponseDependenciesLlm.
        :type model: str
        """

        self._model = model

    @property
    def error(self) -> str:
        """Gets the error of this HealthResponseDependenciesLlm.


        :return: The error of this HealthResponseDependenciesLlm.
        :rtype: str
        """
        return self._error

    @error.setter
    def error(self, error: str):
        """Sets the error of this HealthResponseDependenciesLlm.


        :param error: The error of this HealthResponseDependenciesLlm.
        :type error: str
        """

        self._error = error
