# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.health_response_dependencies_embedding_model import HealthResponseDependenciesEmbeddingModel  # noqa: F401,E501
from swagger_server.models.health_response_dependencies_llm import HealthResponseDependenciesLlm  # noqa: F401,E501
from swagger_server.models.health_response_dependencies_mongodb import HealthResponseDependenciesMongodb  # noqa: F401,E501
from swagger_server import util


class HealthResponseDependencies(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, embedding_model: HealthResponseDependenciesEmbeddingModel=None, mongodb: HealthResponseDependenciesMongodb=None, llm: HealthResponseDependenciesLlm=None):  # noqa: E501
        """HealthResponseDependencies - a model defined in Swagger

        :param embedding_model: The embedding_model of this HealthResponseDependencies.  # noqa: E501
        :type embedding_model: HealthResponseDependenciesEmbeddingModel
        :param mongodb: The mongodb of this HealthResponseDependencies.  # noqa: E501
        :type mongodb: HealthResponseDependenciesMongodb
        :param llm: The llm of this HealthResponseDependencies.  # noqa: E501
        :type llm: HealthResponseDependenciesLlm
        """
        self.swagger_types = {
            'embedding_model': HealthResponseDependenciesEmbeddingModel,
            'mongodb': HealthResponseDependenciesMongodb,
            'llm': HealthResponseDependenciesLlm
        }

        self.attribute_map = {
            'embedding_model': 'embedding_model',
            'mongodb': 'mongodb',
            'llm': 'llm'
        }
        self._embedding_model = embedding_model
        self._mongodb = mongodb
        self._llm = llm

    @classmethod
    def from_dict(cls, dikt) -> 'HealthResponseDependencies':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HealthResponse_dependencies of this HealthResponseDependencies.  # noqa: E501
        :rtype: HealthResponseDependencies
        """
        return util.deserialize_model(dikt, cls)

    @property
    def embedding_model(self) -> HealthResponseDependenciesEmbeddingModel:
        """Gets the embedding_model of this HealthResponseDependencies.


        :return: The embedding_model of this HealthResponseDependencies.
        :rtype: HealthResponseDependenciesEmbeddingModel
        """
        return self._embedding_model

    @embedding_model.setter
    def embedding_model(self, embedding_model: HealthResponseDependenciesEmbeddingModel):
        """Sets the embedding_model of this HealthResponseDependencies.


        :param embedding_model: The embedding_model of this HealthResponseDependencies.
        :type embedding_model: HealthResponseDependenciesEmbeddingModel
        """

        self._embedding_model = embedding_model

    @property
    def mongodb(self) -> HealthResponseDependenciesMongodb:
        """Gets the mongodb of this HealthResponseDependencies.


        :return: The mongodb of this HealthResponseDependencies.
        :rtype: HealthResponseDependenciesMongodb
        """
        return self._mongodb

    @mongodb.setter
    def mongodb(self, mongodb: HealthResponseDependenciesMongodb):
        """Sets the mongodb of this HealthResponseDependencies.


        :param mongodb: The mongodb of this HealthResponseDependencies.
        :type mongodb: HealthResponseDependenciesMongodb
        """

        self._mongodb = mongodb

    @property
    def llm(self) -> HealthResponseDependenciesLlm:
        """Gets the llm of this HealthResponseDependencies.


        :return: The llm of this HealthResponseDependencies.
        :rtype: HealthResponseDependenciesLlm
        """
        return self._llm

    @llm.setter
    def llm(self, llm: HealthResponseDependenciesLlm):
        """Sets the llm of this HealthResponseDependencies.


        :param llm: The llm of this HealthResponseDependencies.
        :type llm: HealthResponseDependenciesLlm
        """

        self._llm = llm
