# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class HealthResponseDependenciesMongodb(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, status: str=None, ping_ms: int=None, error: str=None):  # noqa: E501
        """HealthResponseDependenciesMongodb - a model defined in Swagger

        :param status: The status of this HealthResponseDependenciesMongodb.  # noqa: E501
        :type status: str
        :param ping_ms: The ping_ms of this HealthResponseDependenciesMongodb.  # noqa: E501
        :type ping_ms: int
        :param error: The error of this HealthResponseDependenciesMongodb.  # noqa: E501
        :type error: str
        """
        self.swagger_types = {
            'status': str,
            'ping_ms': int,
            'error': str
        }

        self.attribute_map = {
            'status': 'status',
            'ping_ms': 'ping_ms',
            'error': 'error'
        }
        self._status = status
        self._ping_ms = ping_ms
        self._error = error

    @classmethod
    def from_dict(cls, dikt) -> 'HealthResponseDependenciesMongodb':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HealthResponse_dependencies_mongodb of this HealthResponseDependenciesMongodb.  # noqa: E501
        :rtype: HealthResponseDependenciesMongodb
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> str:
        """Gets the status of this HealthResponseDependenciesMongodb.


        :return: The status of this HealthResponseDependenciesMongodb.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this HealthResponseDependenciesMongodb.


        :param status: The status of this HealthResponseDependenciesMongodb.
        :type status: str
        """
        allowed_values = ["ok", "error"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def ping_ms(self) -> int:
        """Gets the ping_ms of this HealthResponseDependenciesMongodb.


        :return: The ping_ms of this HealthResponseDependenciesMongodb.
        :rtype: int
        """
        return self._ping_ms

    @ping_ms.setter
    def ping_ms(self, ping_ms: int):
        """Sets the ping_ms of this HealthResponseDependenciesMongodb.


        :param ping_ms: The ping_ms of this HealthResponseDependenciesMongodb.
        :type ping_ms: int
        """

        self._ping_ms = ping_ms

    @property
    def error(self) -> str:
        """Gets the error of this HealthResponseDependenciesMongodb.


        :return: The error of this HealthResponseDependenciesMongodb.
        :rtype: str
        """
        return self._error

    @error.setter
    def error(self, error: str):
        """Sets the error of this HealthResponseDependenciesMongodb.


        :param error: The error of this HealthResponseDependenciesMongodb.
        :type error: str
        """

        self._error = error
