# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.health_response_dependencies import HealthResponseDependencies  # noqa: F401,E501
from swagger_server import util


class HealthResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, status: str=None, version: str=None, uptime_seconds: int=None, dependencies: HealthResponseDependencies=None):  # noqa: E501
        """HealthResponse - a model defined in Swagger

        :param status: The status of this HealthResponse.  # noqa: E501
        :type status: str
        :param version: The version of this HealthResponse.  # noqa: E501
        :type version: str
        :param uptime_seconds: The uptime_seconds of this HealthResponse.  # noqa: E501
        :type uptime_seconds: int
        :param dependencies: The dependencies of this HealthResponse.  # noqa: E501
        :type dependencies: HealthResponseDependencies
        """
        self.swagger_types = {
            'status': str,
            'version': str,
            'uptime_seconds': int,
            'dependencies': HealthResponseDependencies
        }

        self.attribute_map = {
            'status': 'status',
            'version': 'version',
            'uptime_seconds': 'uptime_seconds',
            'dependencies': 'dependencies'
        }
        self._status = status
        self._version = version
        self._uptime_seconds = uptime_seconds
        self._dependencies = dependencies

    @classmethod
    def from_dict(cls, dikt) -> 'HealthResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HealthResponse of this HealthResponse.  # noqa: E501
        :rtype: HealthResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> str:
        """Gets the status of this HealthResponse.


        :return: The status of this HealthResponse.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this HealthResponse.


        :param status: The status of this HealthResponse.
        :type status: str
        """
        allowed_values = ["healthy", "degraded", "unhealthy"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def version(self) -> str:
        """Gets the version of this HealthResponse.


        :return: The version of this HealthResponse.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version: str):
        """Sets the version of this HealthResponse.


        :param version: The version of this HealthResponse.
        :type version: str
        """

        self._version = version

    @property
    def uptime_seconds(self) -> int:
        """Gets the uptime_seconds of this HealthResponse.


        :return: The uptime_seconds of this HealthResponse.
        :rtype: int
        """
        return self._uptime_seconds

    @uptime_seconds.setter
    def uptime_seconds(self, uptime_seconds: int):
        """Sets the uptime_seconds of this HealthResponse.


        :param uptime_seconds: The uptime_seconds of this HealthResponse.
        :type uptime_seconds: int
        """

        self._uptime_seconds = uptime_seconds

    @property
    def dependencies(self) -> HealthResponseDependencies:
        """Gets the dependencies of this HealthResponse.


        :return: The dependencies of this HealthResponse.
        :rtype: HealthResponseDependencies
        """
        return self._dependencies

    @dependencies.setter
    def dependencies(self, dependencies: HealthResponseDependencies):
        """Sets the dependencies of this HealthResponse.


        :param dependencies: The dependencies of this HealthResponse.
        :type dependencies: HealthResponseDependencies
        """
        if dependencies is None:
            raise ValueError("Invalid value for `dependencies`, must not be `None`")  # noqa: E501

        self._dependencies = dependencies
