# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class HealthResponseDependenciesEmbeddingModel(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, status: str=None, model: str=None, dimensions: int=None, error: str=None):  # noqa: E501
        """HealthResponseDependenciesEmbeddingModel - a model defined in Swagger

        :param status: The status of this HealthResponseDependenciesEmbeddingModel.  # noqa: E501
        :type status: str
        :param model: The model of this HealthResponseDependenciesEmbeddingModel.  # noqa: E501
        :type model: str
        :param dimensions: The dimensions of this HealthResponseDependenciesEmbeddingModel.  # noqa: E501
        :type dimensions: int
        :param error: The error of this HealthResponseDependenciesEmbeddingModel.  # noqa: E501
        :type error: str
        """
        self.swagger_types = {
            'status': str,
            'model': str,
            'dimensions': int,
            'error': str
        }

        self.attribute_map = {
            'status': 'status',
            'model': 'model',
            'dimensions': 'dimensions',
            'error': 'error'
        }
        self._status = status
        self._model = model
        self._dimensions = dimensions
        self._error = error

    @classmethod
    def from_dict(cls, dikt) -> 'HealthResponseDependenciesEmbeddingModel':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HealthResponse_dependencies_embedding_model of this HealthResponseDependenciesEmbeddingModel.  # noqa: E501
        :rtype: HealthResponseDependenciesEmbeddingModel
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> str:
        """Gets the status of this HealthResponseDependenciesEmbeddingModel.


        :return: The status of this HealthResponseDependenciesEmbeddingModel.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this HealthResponseDependenciesEmbeddingModel.


        :param status: The status of this HealthResponseDependenciesEmbeddingModel.
        :type status: str
        """
        allowed_values = ["ok", "error"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def model(self) -> str:
        """Gets the model of this HealthResponseDependenciesEmbeddingModel.


        :return: The model of this HealthResponseDependenciesEmbeddingModel.
        :rtype: str
        """
        return self._model

    @model.setter
    def model(self, model: str):
        """Sets the model of this HealthResponseDependenciesEmbeddingModel.


        :param model: The model of this HealthResponseDependenciesEmbeddingModel.
        :type model: str
        """

        self._model = model

    @property
    def dimensions(self) -> int:
        """Gets the dimensions of this HealthResponseDependenciesEmbeddingModel.


        :return: The dimensions of this HealthResponseDependenciesEmbeddingModel.
        :rtype: int
        """
        return self._dimensions

    @dimensions.setter
    def dimensions(self, dimensions: int):
        """Sets the dimensions of this HealthResponseDependenciesEmbeddingModel.


        :param dimensions: The dimensions of this HealthResponseDependenciesEmbeddingModel.
        :type dimensions: int
        """

        self._dimensions = dimensions

    @property
    def error(self) -> str:
        """Gets the error of this HealthResponseDependenciesEmbeddingModel.


        :return: The error of this HealthResponseDependenciesEmbeddingModel.
        :rtype: str
        """
        return self._error

    @error.setter
    def error(self, error: str):
        """Sets the error of this HealthResponseDependenciesEmbeddingModel.


        :param error: The error of this HealthResponseDependenciesEmbeddingModel.
        :type error: str
        """

        self._error = error
