# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class IngestBody1(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, text: str=None, source: str=None, collection_name: str='default'):  # noqa: E501
        """IngestBody1 - a model defined in Swagger

        :param text: The text of this IngestBody1.  # noqa: E501
        :type text: str
        :param source: The source of this IngestBody1.  # noqa: E501
        :type source: str
        :param collection_name: The collection_name of this IngestBody1.  # noqa: E501
        :type collection_name: str
        """
        self.swagger_types = {
            'text': str,
            'source': str,
            'collection_name': str
        }

        self.attribute_map = {
            'text': 'text',
            'source': 'source',
            'collection_name': 'collection_name'
        }
        self._text = text
        self._source = source
        self._collection_name = collection_name

    @classmethod
    def from_dict(cls, dikt) -> 'IngestBody1':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ingest_body_1 of this IngestBody1.  # noqa: E501
        :rtype: IngestBody1
        """
        return util.deserialize_model(dikt, cls)

    @property
    def text(self) -> str:
        """Gets the text of this IngestBody1.

        Raw text content to ingest  # noqa: E501

        :return: The text of this IngestBody1.
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text: str):
        """Sets the text of this IngestBody1.

        Raw text content to ingest  # noqa: E501

        :param text: The text of this IngestBody1.
        :type text: str
        """
        if text is None:
            raise ValueError("Invalid value for `text`, must not be `None`")  # noqa: E501

        self._text = text

    @property
    def source(self) -> str:
        """Gets the source of this IngestBody1.

        Identifier for this document (used in citations)  # noqa: E501

        :return: The source of this IngestBody1.
        :rtype: str
        """
        return self._source

    @source.setter
    def source(self, source: str):
        """Sets the source of this IngestBody1.

        Identifier for this document (used in citations)  # noqa: E501

        :param source: The source of this IngestBody1.
        :type source: str
        """
        if source is None:
            raise ValueError("Invalid value for `source`, must not be `None`")  # noqa: E501

        self._source = source

    @property
    def collection_name(self) -> str:
        """Gets the collection_name of this IngestBody1.


        :return: The collection_name of this IngestBody1.
        :rtype: str
        """
        return self._collection_name

    @collection_name.setter
    def collection_name(self, collection_name: str):
        """Sets the collection_name of this IngestBody1.


        :param collection_name: The collection_name of this IngestBody1.
        :type collection_name: str
        """

        self._collection_name = collection_name
