# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class IngestBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, file: str=None, collection_name: str='default'):  # noqa: E501
        """IngestBody - a model defined in Swagger

        :param file: The file of this IngestBody.  # noqa: E501
        :type file: str
        :param collection_name: The collection_name of this IngestBody.  # noqa: E501
        :type collection_name: str
        """
        self.swagger_types = {
            'file': str,
            'collection_name': str
        }

        self.attribute_map = {
            'file': 'file',
            'collection_name': 'collection_name'
        }
        self._file = file
        self._collection_name = collection_name

    @classmethod
    def from_dict(cls, dikt) -> 'IngestBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ingest_body of this IngestBody.  # noqa: E501
        :rtype: IngestBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def file(self) -> str:
        """Gets the file of this IngestBody.

        PDF file to ingest  # noqa: E501

        :return: The file of this IngestBody.
        :rtype: str
        """
        return self._file

    @file.setter
    def file(self, file: str):
        """Sets the file of this IngestBody.

        PDF file to ingest  # noqa: E501

        :param file: The file of this IngestBody.
        :type file: str
        """
        if file is None:
            raise ValueError("Invalid value for `file`, must not be `None`")  # noqa: E501

        self._file = file

    @property
    def collection_name(self) -> str:
        """Gets the collection_name of this IngestBody.

        Logical collection name to group documents  # noqa: E501

        :return: The collection_name of this IngestBody.
        :rtype: str
        """
        return self._collection_name

    @collection_name.setter
    def collection_name(self, collection_name: str):
        """Sets the collection_name of this IngestBody.

        Logical collection name to group documents  # noqa: E501

        :param collection_name: The collection_name of this IngestBody.
        :type collection_name: str
        """

        self._collection_name = collection_name
