# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class IngestResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, chunk_count: int=None, source: str=None, collection_name: str=None, ingested_at: datetime=None):  # noqa: E501
        """IngestResponse - a model defined in Swagger

        :param chunk_count: The chunk_count of this IngestResponse.  # noqa: E501
        :type chunk_count: int
        :param source: The source of this IngestResponse.  # noqa: E501
        :type source: str
        :param collection_name: The collection_name of this IngestResponse.  # noqa: E501
        :type collection_name: str
        :param ingested_at: The ingested_at of this IngestResponse.  # noqa: E501
        :type ingested_at: datetime
        """
        self.swagger_types = {
            'chunk_count': int,
            'source': str,
            'collection_name': str,
            'ingested_at': datetime
        }

        self.attribute_map = {
            'chunk_count': 'chunk_count',
            'source': 'source',
            'collection_name': 'collection_name',
            'ingested_at': 'ingested_at'
        }
        self._chunk_count = chunk_count
        self._source = source
        self._collection_name = collection_name
        self._ingested_at = ingested_at

    @classmethod
    def from_dict(cls, dikt) -> 'IngestResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The IngestResponse of this IngestResponse.  # noqa: E501
        :rtype: IngestResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def chunk_count(self) -> int:
        """Gets the chunk_count of this IngestResponse.

        Number of chunks created and stored in MongoDB  # noqa: E501

        :return: The chunk_count of this IngestResponse.
        :rtype: int
        """
        return self._chunk_count

    @chunk_count.setter
    def chunk_count(self, chunk_count: int):
        """Sets the chunk_count of this IngestResponse.

        Number of chunks created and stored in MongoDB  # noqa: E501

        :param chunk_count: The chunk_count of this IngestResponse.
        :type chunk_count: int
        """
        if chunk_count is None:
            raise ValueError("Invalid value for `chunk_count`, must not be `None`")  # noqa: E501

        self._chunk_count = chunk_count

    @property
    def source(self) -> str:
        """Gets the source of this IngestResponse.

        Identifier for the ingested document  # noqa: E501

        :return: The source of this IngestResponse.
        :rtype: str
        """
        return self._source

    @source.setter
    def source(self, source: str):
        """Sets the source of this IngestResponse.

        Identifier for the ingested document  # noqa: E501

        :param source: The source of this IngestResponse.
        :type source: str
        """
        if source is None:
            raise ValueError("Invalid value for `source`, must not be `None`")  # noqa: E501

        self._source = source

    @property
    def collection_name(self) -> str:
        """Gets the collection_name of this IngestResponse.

        Logical collection the document was stored in  # noqa: E501

        :return: The collection_name of this IngestResponse.
        :rtype: str
        """
        return self._collection_name

    @collection_name.setter
    def collection_name(self, collection_name: str):
        """Sets the collection_name of this IngestResponse.

        Logical collection the document was stored in  # noqa: E501

        :param collection_name: The collection_name of this IngestResponse.
        :type collection_name: str
        """
        if collection_name is None:
            raise ValueError("Invalid value for `collection_name`, must not be `None`")  # noqa: E501

        self._collection_name = collection_name

    @property
    def ingested_at(self) -> datetime:
        """Gets the ingested_at of this IngestResponse.

        UTC timestamp of ingestion  # noqa: E501

        :return: The ingested_at of this IngestResponse.
        :rtype: datetime
        """
        return self._ingested_at

    @ingested_at.setter
    def ingested_at(self, ingested_at: datetime):
        """Sets the ingested_at of this IngestResponse.

        UTC timestamp of ingestion  # noqa: E501

        :param ingested_at: The ingested_at of this IngestResponse.
        :type ingested_at: datetime
        """
        if ingested_at is None:
            raise ValueError("Invalid value for `ingested_at`, must not be `None`")  # noqa: E501

        self._ingested_at = ingested_at
