# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, deleted_count: int=None, source: str=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param deleted_count: The deleted_count of this InlineResponse200.  # noqa: E501
        :type deleted_count: int
        :param source: The source of this InlineResponse200.  # noqa: E501
        :type source: str
        """
        self.swagger_types = {
            'deleted_count': int,
            'source': str
        }

        self.attribute_map = {
            'deleted_count': 'deleted_count',
            'source': 'source'
        }
        self._deleted_count = deleted_count
        self._source = source

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def deleted_count(self) -> int:
        """Gets the deleted_count of this InlineResponse200.


        :return: The deleted_count of this InlineResponse200.
        :rtype: int
        """
        return self._deleted_count

    @deleted_count.setter
    def deleted_count(self, deleted_count: int):
        """Sets the deleted_count of this InlineResponse200.


        :param deleted_count: The deleted_count of this InlineResponse200.
        :type deleted_count: int
        """

        self._deleted_count = deleted_count

    @property
    def source(self) -> str:
        """Gets the source of this InlineResponse200.


        :return: The source of this InlineResponse200.
        :rtype: str
        """
        return self._source

    @source.setter
    def source(self, source: str):
        """Sets the source of this InlineResponse200.


        :param source: The source of this InlineResponse200.
        :type source: str
        """

        self._source = source
