# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.source_chunk import SourceChunk  # noqa: F401,E501
from swagger_server import util


class QueryResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, answer: str=None, sources: List[SourceChunk]=None, model_used: str=None, latency_ms: int=None):  # noqa: E501
        """QueryResponse - a model defined in Swagger

        :param answer: The answer of this QueryResponse.  # noqa: E501
        :type answer: str
        :param sources: The sources of this QueryResponse.  # noqa: E501
        :type sources: List[SourceChunk]
        :param model_used: The model_used of this QueryResponse.  # noqa: E501
        :type model_used: str
        :param latency_ms: The latency_ms of this QueryResponse.  # noqa: E501
        :type latency_ms: int
        """
        self.swagger_types = {
            'answer': str,
            'sources': List[SourceChunk],
            'model_used': str,
            'latency_ms': int
        }

        self.attribute_map = {
            'answer': 'answer',
            'sources': 'sources',
            'model_used': 'model_used',
            'latency_ms': 'latency_ms'
        }
        self._answer = answer
        self._sources = sources
        self._model_used = model_used
        self._latency_ms = latency_ms

    @classmethod
    def from_dict(cls, dikt) -> 'QueryResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The QueryResponse of this QueryResponse.  # noqa: E501
        :rtype: QueryResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def answer(self) -> str:
        """Gets the answer of this QueryResponse.

        LLM-generated answer grounded in retrieved context  # noqa: E501

        :return: The answer of this QueryResponse.
        :rtype: str
        """
        return self._answer

    @answer.setter
    def answer(self, answer: str):
        """Sets the answer of this QueryResponse.

        LLM-generated answer grounded in retrieved context  # noqa: E501

        :param answer: The answer of this QueryResponse.
        :type answer: str
        """
        if answer is None:
            raise ValueError("Invalid value for `answer`, must not be `None`")  # noqa: E501

        self._answer = answer

    @property
    def sources(self) -> List[SourceChunk]:
        """Gets the sources of this QueryResponse.

        Chunks retrieved from MongoDB used to generate the answer  # noqa: E501

        :return: The sources of this QueryResponse.
        :rtype: List[SourceChunk]
        """
        return self._sources

    @sources.setter
    def sources(self, sources: List[SourceChunk]):
        """Sets the sources of this QueryResponse.

        Chunks retrieved from MongoDB used to generate the answer  # noqa: E501

        :param sources: The sources of this QueryResponse.
        :type sources: List[SourceChunk]
        """
        if sources is None:
            raise ValueError("Invalid value for `sources`, must not be `None`")  # noqa: E501

        self._sources = sources

    @property
    def model_used(self) -> str:
        """Gets the model_used of this QueryResponse.

        LLM model that generated the answer  # noqa: E501

        :return: The model_used of this QueryResponse.
        :rtype: str
        """
        return self._model_used

    @model_used.setter
    def model_used(self, model_used: str):
        """Sets the model_used of this QueryResponse.

        LLM model that generated the answer  # noqa: E501

        :param model_used: The model_used of this QueryResponse.
        :type model_used: str
        """

        self._model_used = model_used

    @property
    def latency_ms(self) -> int:
        """Gets the latency_ms of this QueryResponse.

        Total request processing time in milliseconds  # noqa: E501

        :return: The latency_ms of this QueryResponse.
        :rtype: int
        """
        return self._latency_ms

    @latency_ms.setter
    def latency_ms(self, latency_ms: int):
        """Sets the latency_ms of this QueryResponse.

        Total request processing time in milliseconds  # noqa: E501

        :param latency_ms: The latency_ms of this QueryResponse.
        :type latency_ms: int
        """

        self._latency_ms = latency_ms
