# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class QueryRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, question: str=None, top_k: int=4, source_filter: str=None, collection_name: str='default'):  # noqa: E501
        """QueryRequest - a model defined in Swagger

        :param question: The question of this QueryRequest.  # noqa: E501
        :type question: str
        :param top_k: The top_k of this QueryRequest.  # noqa: E501
        :type top_k: int
        :param source_filter: The source_filter of this QueryRequest.  # noqa: E501
        :type source_filter: str
        :param collection_name: The collection_name of this QueryRequest.  # noqa: E501
        :type collection_name: str
        """
        self.swagger_types = {
            'question': str,
            'top_k': int,
            'source_filter': str,
            'collection_name': str
        }

        self.attribute_map = {
            'question': 'question',
            'top_k': 'top_k',
            'source_filter': 'source_filter',
            'collection_name': 'collection_name'
        }
        self._question = question
        self._top_k = top_k
        self._source_filter = source_filter
        self._collection_name = collection_name

    @classmethod
    def from_dict(cls, dikt) -> 'QueryRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The QueryRequest of this QueryRequest.  # noqa: E501
        :rtype: QueryRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def question(self) -> str:
        """Gets the question of this QueryRequest.

        Natural language question to answer  # noqa: E501

        :return: The question of this QueryRequest.
        :rtype: str
        """
        return self._question

    @question.setter
    def question(self, question: str):
        """Sets the question of this QueryRequest.

        Natural language question to answer  # noqa: E501

        :param question: The question of this QueryRequest.
        :type question: str
        """
        if question is None:
            raise ValueError("Invalid value for `question`, must not be `None`")  # noqa: E501

        self._question = question

    @property
    def top_k(self) -> int:
        """Gets the top_k of this QueryRequest.

        Number of chunks to retrieve for context (overrides server default)  # noqa: E501

        :return: The top_k of this QueryRequest.
        :rtype: int
        """
        return self._top_k

    @top_k.setter
    def top_k(self, top_k: int):
        """Sets the top_k of this QueryRequest.

        Number of chunks to retrieve for context (overrides server default)  # noqa: E501

        :param top_k: The top_k of this QueryRequest.
        :type top_k: int
        """

        self._top_k = top_k

    @property
    def source_filter(self) -> str:
        """Gets the source_filter of this QueryRequest.

        Restrict retrieval to chunks from a specific source document  # noqa: E501

        :return: The source_filter of this QueryRequest.
        :rtype: str
        """
        return self._source_filter

    @source_filter.setter
    def source_filter(self, source_filter: str):
        """Sets the source_filter of this QueryRequest.

        Restrict retrieval to chunks from a specific source document  # noqa: E501

        :param source_filter: The source_filter of this QueryRequest.
        :type source_filter: str
        """

        self._source_filter = source_filter

    @property
    def collection_name(self) -> str:
        """Gets the collection_name of this QueryRequest.

        Query within a specific logical collection  # noqa: E501

        :return: The collection_name of this QueryRequest.
        :rtype: str
        """
        return self._collection_name

    @collection_name.setter
    def collection_name(self, collection_name: str):
        """Sets the collection_name of this QueryRequest.

        Query within a specific logical collection  # noqa: E501

        :param collection_name: The collection_name of this QueryRequest.
        :type collection_name: str
        """

        self._collection_name = collection_name
