# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SourceChunk(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, text: str=None, source: str=None, page: int=None, chunk_index: int=None, score: float=None):  # noqa: E501
        """SourceChunk - a model defined in Swagger

        :param text: The text of this SourceChunk.  # noqa: E501
        :type text: str
        :param source: The source of this SourceChunk.  # noqa: E501
        :type source: str
        :param page: The page of this SourceChunk.  # noqa: E501
        :type page: int
        :param chunk_index: The chunk_index of this SourceChunk.  # noqa: E501
        :type chunk_index: int
        :param score: The score of this SourceChunk.  # noqa: E501
        :type score: float
        """
        self.swagger_types = {
            'text': str,
            'source': str,
            'page': int,
            'chunk_index': int,
            'score': float
        }

        self.attribute_map = {
            'text': 'text',
            'source': 'source',
            'page': 'page',
            'chunk_index': 'chunk_index',
            'score': 'score'
        }
        self._text = text
        self._source = source
        self._page = page
        self._chunk_index = chunk_index
        self._score = score

    @classmethod
    def from_dict(cls, dikt) -> 'SourceChunk':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SourceChunk of this SourceChunk.  # noqa: E501
        :rtype: SourceChunk
        """
        return util.deserialize_model(dikt, cls)

    @property
    def text(self) -> str:
        """Gets the text of this SourceChunk.

        The raw chunk text used as context  # noqa: E501

        :return: The text of this SourceChunk.
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text: str):
        """Sets the text of this SourceChunk.

        The raw chunk text used as context  # noqa: E501

        :param text: The text of this SourceChunk.
        :type text: str
        """
        if text is None:
            raise ValueError("Invalid value for `text`, must not be `None`")  # noqa: E501

        self._text = text

    @property
    def source(self) -> str:
        """Gets the source of this SourceChunk.

        Source document identifier  # noqa: E501

        :return: The source of this SourceChunk.
        :rtype: str
        """
        return self._source

    @source.setter
    def source(self, source: str):
        """Sets the source of this SourceChunk.

        Source document identifier  # noqa: E501

        :param source: The source of this SourceChunk.
        :type source: str
        """
        if source is None:
            raise ValueError("Invalid value for `source`, must not be `None`")  # noqa: E501

        self._source = source

    @property
    def page(self) -> int:
        """Gets the page of this SourceChunk.

        Page number (PDF sources only)  # noqa: E501

        :return: The page of this SourceChunk.
        :rtype: int
        """
        return self._page

    @page.setter
    def page(self, page: int):
        """Sets the page of this SourceChunk.

        Page number (PDF sources only)  # noqa: E501

        :param page: The page of this SourceChunk.
        :type page: int
        """

        self._page = page

    @property
    def chunk_index(self) -> int:
        """Gets the chunk_index of this SourceChunk.

        Sequential chunk index within the source document  # noqa: E501

        :return: The chunk_index of this SourceChunk.
        :rtype: int
        """
        return self._chunk_index

    @chunk_index.setter
    def chunk_index(self, chunk_index: int):
        """Sets the chunk_index of this SourceChunk.

        Sequential chunk index within the source document  # noqa: E501

        :param chunk_index: The chunk_index of this SourceChunk.
        :type chunk_index: int
        """

        self._chunk_index = chunk_index

    @property
    def score(self) -> float:
        """Gets the score of this SourceChunk.

        Cosine similarity score between this chunk and the query (0–1)  # noqa: E501

        :return: The score of this SourceChunk.
        :rtype: float
        """
        return self._score

    @score.setter
    def score(self, score: float):
        """Sets the score of this SourceChunk.

        Cosine similarity score between this chunk and the query (0–1)  # noqa: E501

        :param score: The score of this SourceChunk.
        :type score: float
        """
        if score is None:
            raise ValueError("Invalid value for `score`, must not be `None`")  # noqa: E501

        self._score = score
